# -*- coding: utf-8 -*-
"""
Tests for US company-name -> ticker alias resolution in normalize_stock_code.
"""

import pytest

from data_provider.base import US_SYMBOL_ALIASES, normalize_stock_code


class TestUsSymbolAliases:
    @pytest.mark.parametrize(
        ("name", "ticker"),
        [
            ("APPLE", "AAPL"),
            ("apple", "AAPL"),
            ("APPLE.US", "AAPL"),
            ("MICROSOFT", "MSFT"),
            ("GOOGLE", "GOOGL"),
            ("ALPHABET", "GOOGL"),
            ("AMAZON", "AMZN"),
            ("TESLA", "TSLA"),
            ("NVIDIA", "NVDA"),
            ("NETFLIX", "NFLX"),
            ("FACEBOOK", "META"),
            ("INTEL", "INTC"),
            ("CISCO", "CSCO"),
            ("ORACLE", "ORCL"),
            ("ADOBE", "ADBE"),
            ("QUALCOMM", "QCOM"),
            ("HP", "HPQ"),
            ("NIKE", "NKE"),
            ("PEPSI", "PEP"),
            ("MERCK", "MRK"),
            ("EXXON", "XOM"),
            ("SHELL", "SHEL"),
            ("DELTA", "DAL"),
            ("FEDEX", "FDX"),
            ("LOWES", "LOW"),
            ("GAP", "GPS"),
            ("HONDA", "HMC"),
            ("DEERE", "DE"),
            ("ZOOM", "ZM"),
            ("BAIDU", "BIDU"),
            ("XPENG", "XPEV"),
            ("LUCID", "LCID"),
            ("BLOCK", "XYZ"),
            ("CHASE", "JPM"),
            ("AMEX", "AXP"),
            ("ALIBABA", "BABA"),
            ("BILIBILI", "BILI"),
            ("RIVIAN", "RIVN"),
            ("SHOPIFY", "SHOP"),
            ("AIRBNB", "ABNB"),
            ("COINBASE", "COIN"),
            ("PALANTIR", "PLTR"),
            ("SNOWFLAKE", "SNOW"),
            ("ROBINHOOD", "HOOD"),
            ("SPOTIFY", "SPOT"),
            ("SALESFORCE", "CRM"),
            ("WORKDAY", "WDAY"),
            ("SERVICENOW", "NOW"),
            ("AUTODESK", "ADSK"),
            ("INTUIT", "INTU"),
            ("TWILIO", "TWLO"),
            ("DROPBOX", "DBX"),
            ("PINTEREST", "PINS"),
            ("MASTERCARD", "MA"),
            ("GOLDMAN", "GS"),
            ("JPMORGAN", "JPM"),
            ("CITIGROUP", "C"),
            ("UNITEDHEALTH", "UNH"),
            ("PROCTER", "PG"),
            ("COLGATE", "CL"),
            ("HONEYWELL", "HON"),
            ("CATERPILLAR", "CAT"),
            ("LOCKHEED", "LMT"),
            ("NORTHROP", "NOC"),
            ("RAYTHEON", "RTX"),
            ("SOUTHWEST", "LUV"),
            ("NORFOLK", "NSC"),
            ("LULULEMON", "LULU"),
            ("BOEING", "BA"),
            ("DISNEY", "DIS"),
            ("WALMART", "WMT"),
            ("COSTCO", "COST"),
            ("TARGET", "TGT"),
            ("STARBUCKS", "SBUX"),
            ("MCDONALDS", "MCD"),
            ("COCACOLA", "KO"),
            ("TOYOTA", "TM"),
            ("PFIZER", "PFE"),
            ("ABBOTT", "ABT"),
            ("CHEVRON", "CVX"),
            ("CONOCOPHILLIPS", "COP"),
            ("DUPONT", "DD"),
            ("GENERALELECTRIC", "GE"),
            ("GENERALMOTORS", "GM"),
            ("HOMEDEPOT", "HD"),
            ("WALTDISNEY", "DIS"),
            ("AMERICANEXPRESS", "AXP"),
            ("GOLDMANSACHS", "GS"),
            ("MORGANSTANLEY", "MS"),
            ("BANKOFAMERICA", "BAC"),
            ("WELLSFARGO", "WFC"),
            ("JOHNSONJOHNSON", "JNJ"),
            ("PROCTERGAMBLE", "PG"),
            ("UNITEDAIRLINES", "UAL"),
            ("AMERICANAIRLINES", "AAL"),
            ("DELTAAIRLINES", "DAL"),
            ("SOUTHWESTAIRLINES", "LUV"),
            ("TSMC", "TSM"),
            ("NETEASE", "NTES"),
            ("PINDDUODUO", "PDD"),
        ],
    )
    def test_resolves_company_name_to_ticker(self, name: str, ticker: str) -> None:
        assert normalize_stock_code(name) == ticker

    @pytest.mark.parametrize(
        "code",
        [
            "AAPL",
            "TSLA",
            "MSFT",
            "GOOGL",
            "GOOG",
            "AMZN",
            "NVDA",
            "NFLX",
            "META",
            "INTC",
            "CSCO",
            "ORCL",
            "ADBE",
            "QCOM",
            "HPQ",
            "NKE",
            "PEP",
            "MRK",
            "XOM",
            "SHEL",
            "DAL",
            "FDX",
            "LOW",
            "GPS",
            "HMC",
            "DE",
            "ZM",
            "BIDU",
            "XPEV",
            "LCID",
            "XYZ",
            "JPM",
            "AXP",
            "BABA",
            "BILI",
            "RIVN",
            "SHOP",
            "ABNB",
            "COIN",
            "PLTR",
            "SNOW",
            "HOOD",
            "SPOT",
            "CRM",
            "WDAY",
            "NOW",
            "ADSK",
            "INTU",
            "TWLO",
            "DBX",
            "PINS",
            "MA",
            "GS",
            "C",
            "UNH",
            "PG",
            "CL",
            "HON",
            "CAT",
            "LMT",
            "NOC",
            "RTX",
            "LUV",
            "NSC",
            "LULU",
            "BA",
            "DIS",
            "WMT",
            "COST",
            "TGT",
            "SBUX",
            "MCD",
            "KO",
            "TM",
            "PFE",
            "ABT",
            "CVX",
            "COP",
            "DD",
            "GE",
            "GM",
            "HD",
            "BAC",
            "WFC",
            "JNJ",
            "UAL",
            "AAL",
            "TSM",
            "NTES",
            "PDD",
            "BRK.B",
            "7203.T",
            "005930.KS",
            "2330.TW",
            "6505.TWO",
            "600519",
            "000001",
            "920748",
            "HK00700",
            "HK01810",
        ],
    )
    def test_keeps_valid_codes_unchanged(self, code: str) -> None:
        assert normalize_stock_code(code) == code

    def test_alias_map_keys_are_not_real_tickers(self) -> None:
            """Alias keys must not collide with real tickers (only names are mapped).

            is_us_stock_code() only checks the 1-5 letter format, so it cannot
            distinguish names from real symbols. Instead, verify that every alias
            key resolves to a different value (i.e. the map actually changes the
            code) and that no key equals its own value (a no-op entry).
            """
            for name, ticker in US_SYMBOL_ALIASES.items():
                assert name != ticker, f"alias entry {name!r} -> {ticker!r} is a no-op"
                assert normalize_stock_code(name) == ticker